trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - azure-pipelines.prod.yml

name: 0.1.$(rev:r)

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: '206f95a6-9c4e-4868-9f2e-588ae6d5050f'
  - name: containerRegistry
    value: 'bitsregistry.azurecr.io'
  - name: debug
    value: true
  - name: imageRepository
    value: 'tamweb'
  - name: dockerfilePath
    value: '**/Dockerfile'
  - name: tag
    value: '$(Build.BuildNumber)'

  # Key vault
  - group: variables-tam-aks-test

  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    - task: replacetokens@3
      inputs:
        targetFiles: 'manifests/*.yml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - upload: manifests
      artifact: manifests
    - task: WhiteSource@20
      displayName: WhiteSource

- stage: Deploy
  displayName: Deploy stage
  jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: $(vmImageName)
      environment: $(cluster).$(namespace)
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                action: deploy
                manifests: |
                  $(Pipeline.Workspace)/manifests/*.yml
