trigger: none

name: 0.1.154

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: '206f95a6-9c4e-4868-9f2e-588ae6d5050f'
  - name: containerRegistry
    value: 'bitsregistry.azurecr.io'
  - name: debug
    value: true
  - name: imageRepository
    value: 'tamweb'
  - name: dockerfilePath
    value: '**/Dockerfile'
  - name: tag
    value: '$(Build.BuildNumber)'

  # Key vault
  - group: variables-tam-aks-prod

  # Agent VM image name
  - name: vmImageName
    value: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: replacetokens@3
      inputs:
        targetFiles: 'manifests/*.yml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: $(vmImageName)
      environment: $(cluster).$(namespace)
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes cluster
              inputs:
                action: deploy
                manifests: |
                  $(Pipeline.Workspace)/manifests/*.yml