apiVersion : apps/v1
kind: Deployment
metadata:
  name: deploy-tam-web
  namespace: #{namespace}#
  labels:
    app: deploy-tam-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-tam-web
  template:
    metadata:
      labels:
        app: deploy-tam-web
    spec:
      containers:
        - name: ctr-tam-web
          image: bitsregistry.azurecr.io/tamweb:#{tag}#
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              value: akvs-tam-appinsights-instrumentationkey@azurekeyvault

---

apiVersion: v1
kind: Service
metadata:
    name: svc-tam-web
    namespace: #{namespace}#
spec:
    ports:
    - port: 80
    selector:
        app: deploy-tam-web

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-tam-web
spec:
  minAvailable: "50%"
  selector:
    matchLabels:
      app: deploy-tam-web